[workspace]
resolver = "2"
members = [
    "crates/lamina-lang",
    "crates/lamina-cli",
    "crates/lamina-llb",
    "crates/lamina-client",
    "crates/lamina-lsp",
]
default-members = ["crates/lamina-cli"]

[workspace.package]
version = "1.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/VitorRamos/lamina"
rust-version = "1.74"

[workspace.dependencies]
lamina-lang = { path = "crates/lamina-lang", version = "1.3.1" }
lamina-llb = { path = "crates/lamina-llb", version = "1.3.1" }
lamina-client = { path = "crates/lamina-client", version = "1.3.1" }
lamina-lsp = { path = "crates/lamina-lsp", version = "1.3.1" }
clap = { version = "4.5", features = ["derive"] }
