//! Path module lockfile (`Lamina.lock`).

use crate::diag::{CompileError, DiagnosticMsg};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub const LOCK_VERSION: u32 = 1;
pub const LOCK_FILE_NAME: &str = "Lamina.lock";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LaminaLock {
    pub version: u32,
    /// Sorted map: use-spec (as written) → entry
    pub modules: BTreeMap<String, LockModule>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockModule {
    /// Path relative to project root when under root; otherwise `std:…` or absolute display
    pub resolved: String,
    pub sha256: String,
}

#[derive(Debug, Clone)]
pub struct ResolvedModule {
    pub spec: String,
    pub path: PathBuf,
    pub sha256: String,
}

impl LaminaLock {
    pub fn from_resolved(modules: &[ResolvedModule], project_root: &Path) -> Self {
        let mut map = BTreeMap::new();
        for m in modules {
            let resolved = display_resolved(&m.path, project_root);
            map.insert(
                m.spec.clone(),
                LockModule {
                    resolved,
                    sha256: m.sha256.clone(),
                },
            );
        }
        Self {
            version: LOCK_VERSION,
            modules: map,
        }
    }

    pub fn load(path: &Path) -> std::result::Result<Self, String> {
        let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
        toml::from_str(&text).map_err(|e| e.to_string())
    }

    pub fn save(&self, path: &Path) -> std::result::Result<(), String> {
        let text = toml::to_string_pretty(self).map_err(|e| e.to_string())?;
        let header = "# This file is generated by `lamina lock`. Do not edit by hand.\n\
# It pins path/stdlib module contents (sha256) for reproducible builds.\n\n";
        std::fs::write(path, format!("{header}{text}")).map_err(|e| e.to_string())
    }

    /// Verify resolved modules match the lock. Errors if locked and mismatch/missing.
    pub fn verify(
        &self,
        resolved: &[ResolvedModule],
        project_root: &Path,
    ) -> std::result::Result<(), CompileError> {
        if self.version != LOCK_VERSION {
            return Err(CompileError::single(
                None,
                DiagnosticMsg::error(
                    format!(
                        "Lamina.lock version {} unsupported (want {LOCK_VERSION})",
                        self.version
                    ),
                    None,
                ),
            ));
        }
        let current = LaminaLock::from_resolved(resolved, project_root);
        for (spec, want) in &self.modules {
            match current.modules.get(spec) {
                None => {
                    return Err(CompileError::single(
                        None,
                        DiagnosticMsg::error(
                            format!(
                                "locked module `{spec}` not used by current sources (run `lamina lock`)"
                            ),
                            None,
                        ),
                    ));
                }
                Some(got) if got.sha256 != want.sha256 => {
                    return Err(CompileError::single(
                        None,
                        DiagnosticMsg::error(
                            format!(
                                "module `{spec}` hash mismatch (locked {}, got {}) — run `lamina lock`",
                                want.sha256, got.sha256
                            ),
                            None,
                        ),
                    ));
                }
                Some(got) if got.resolved != want.resolved => {
                    return Err(CompileError::single(
                        None,
                        DiagnosticMsg::error(
                            format!(
                                "module `{spec}` path changed (locked {}, now {}) — run `lamina lock`",
                                want.resolved, got.resolved
                            ),
                            None,
                        ),
                    ));
                }
                Some(_) => {}
            }
        }
        for spec in current.modules.keys() {
            if !self.modules.contains_key(spec) {
                return Err(CompileError::single(
                    None,
                    DiagnosticMsg::error(
                        format!("module `{spec}` not in Lamina.lock (run `lamina lock`)"),
                        None,
                    ),
                ));
            }
        }
        Ok(())
    }
}

pub fn hash_file(path: &Path) -> std::result::Result<String, String> {
    let bytes = std::fs::read(path).map_err(|e| e.to_string())?;
    let mut h = Sha256::new();
    h.update(&bytes);
    Ok(hex::encode(h.finalize()))
}

fn display_resolved(path: &Path, project_root: &Path) -> String {
    let root = project_root
        .canonicalize()
        .unwrap_or_else(|_| project_root.to_path_buf());
    if let Ok(c) = path.canonicalize() {
        if let Ok(rel) = c.strip_prefix(&root) {
            return rel.display().to_string().replace('\\', "/");
        }
        return c.display().to_string();
    }
    path.display().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn roundtrip_lock() {
        let dir = tempdir().unwrap();
        let f = dir.path().join("a.lam");
        std::fs::write(&f, "pub fn x() -> Int { 1 }\n").unwrap();
        let sha = hash_file(&f).unwrap();
        let lock = LaminaLock::from_resolved(
            &[ResolvedModule {
                spec: "./a.lam".into(),
                path: f.clone(),
                sha256: sha.clone(),
            }],
            dir.path(),
        );
        let p = dir.path().join(LOCK_FILE_NAME);
        lock.save(&p).unwrap();
        let loaded = LaminaLock::load(&p).unwrap();
        assert_eq!(loaded.modules["./a.lam"].sha256, sha);
        loaded
            .verify(
                &[ResolvedModule {
                    spec: "./a.lam".into(),
                    path: f,
                    sha256: sha,
                }],
                dir.path(),
            )
            .unwrap();
    }
}
